---
- name: create vm
  hosts: localhost
  become: false
  gather_facts: false
  collections:
    - community.vmware
  pre_tasks:
      - include_vars: vars.yml
  tasks:
      - name: create folder
        vcenter_folder:
          hostname: vc3.svt.local
          username: administrator@vsphere.local
          password: P@ssw0rdSVT
          validate_certs: false
          datacenter_name: Datacenter
          folder_name: myvm
          folder_type: vm
          state: present
      - name: create VM
        vmware_guest:
          hostname: vc3.svt.local
          username: administrator@vsphere.local
          password: P@ssw0rdSVT
          validate_certs: false
          datacenter: Datacenter
          name: myvm
          folder: myvm
          state: poweroff
          guest_id: TestVM
          cluster: Cluster 3
          disk:
            - size_gb: 10
              type: thin
              datastore: 23.15 localDS
          hardware:
            memory_mb: 1024
            num_cpus: 1
            scsi: paravirtual
          networks:
            - name: 192.168.0.x/24
              device_name: vmxnet3
