---
- name: create vm
  hosts: localhost
  become: false
  gather_facts: false
  collections:
    - community.vmware
  tasks:
      - name: create VM
        vmware_guest:
          hostname: vc3.svt.local
          username: administrator@vsphere.local
          password: P@ssw0rdSVT
          validate_certs: false
          datacenter: Datacenter
          name: myvm1
          folder: myvm
          state: poweredoff
          template: wintemplate
          cluster: Cluster 3
          disk: 
            - size_gb: 40
              type: thin
              datastore: 23.15 localDS
          hardware:
            memory_mb: 1024
            num_cpus: 2
            scsi: paravirtual
            hotadd_cpu: True
            hotremove_cpu: True
            hotadd_memory: False
            boot_firmware: "efi"
          networks:
            - name: 192.168.0.x/24
              device_name: vmxnet3
          customization:
            dns_servers: 8.8.8.8

