---
- name: Create Cluster
  hosts: localhosts
  become: false
  gather_facts: false
  pre_task:
    - include_vars: var.yml
  community.vmware.vmware_cluster:
    hostname: '{{ vcenter_hostname }}'
    username: '{{ vcenter_username }}'
    password: '{{ vcenter_password }}'
    datacenter_name: datacenter
    cluster_name: cluster
  delegate_to: localhost