---
- name: Create dvsSwitch
  hosts: localhosts
  become: false
  gather_facts: false
  collections:
    - community.vmware
##  pre_tasks:
##    - include_vars: var.yml
  tasks:
      - name: Create dvSwitch
        community.vmware.vmware_dvswitch:
          hostname: vc3.svt.local
          username: administrator@vsphere.local
          password: P@ssw0rdSVT
          datacenter: Datacenter
          switch: dvSwitch
          version: 7.0.0
          mtu: 9000
          uplink_quantity: 2
          discovery_protocol: lldp
          discovery_operation: both
          state: present