---
- name: Create dvsSwitch
  hosts: localhosts
  become: false
  gather_facts: false
  collections:
    - community.vmware
  pre_tasks:
    - include_vars: var.yml
  tasks:
      - name: Create dvSwitch
        community.vmware.vmware_dvswitch:
          hostname: '{{ vcenter_hostname }}'
          username: '{{ vcenter_username }}'
          password: '{{ vcenter_password }}'
          datacenter: '{{ datacenter }}'
          switch: dvSwitch
          version: 7.0.0
          mtu: 9000
          uplink_quantity: 2
          discovery_protocol: lldp
          discovery_operation: both
          state: present
        delegate_to: localhost
  