
- name: Virutal Machine - Snapshot, Shutdown, Upgrade Hardware, verify, Power on
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Gather all registered virtual machines
      community.vmware.vcenter_extension_info:
        hostname: vc3.svt.local
        username: administrator@vsphere.local
        password: P@ssw0rdSVT
        vm_type: vm
        validate_certs: no
      delegate_to: localhost
      register: vminfo

    - debug:
        var: vminfo
