---
- name: Upgrade Esxi Host to version 7.0.3l
  hosts: localhost
  become: false
  gather_facts: false
  collections:
    - community.vmware
#  pre_tasks:
##    - include_vars: var.yml
  tasks:
      - name: Upgrade Host to 7.0.3x
        community.vmware.vmware_maintenancemode:
#        community.vmware.vmware_host:
          hostname: vc3.svt.local
          username: administrator@vsphere.local
          password: P@ssw0rdSVT
          validate_certs: false
          datacenter: Datacenter
          cluster: Cluster 2 Node
          esxi_hostname: 192.168.23.14
          esxi_username: root
          esxi_password: P@ssw0rd
          vsan: ensureObjectAccessibility
          evacuate: True
          validate_certs: no
          timeout: 3600
          state: present
          shell: esxcli software profile update -p ESXi-7.0U3l-21424296-standard -d /vmfs/volumes/647241ae-5f3419d0-09dc-00505683937b/ISO/VMware-ESXi-7.0U3l-21424296-depot.zip