---
- name: Upgrade Esxi Host to version 7.0.3l
  hosts: localhost
  become: false
  gather_facts: false
  collections:
    - community.vmware
#  pre_tasks:
##    - include_vars: var.yml
  tasks:
      - name: Upgrade Host to 7.0.3x
        community.vmware.vmware_host:
          hostname: vc3.svt.local
          username: administrator@vsphere.local
          password: P@ssw0rdSVT
          validate_certs: false
          datacenter: Datacenter
          esxi_hostname: 192.168.23.14
          esxi_username: root
          esxi_password: P@ssw0rd